# Generated by Django 3.2.8 on 2021-10-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='code',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='banks.bank')),
            ],
        ),
    ]
