# Generated by Django 3.2.8 on 2021-10-08 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20211008_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_no',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='inital_balance',
            new_name='balance',
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banks.bank'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
